name: search_qiita_articles
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.2
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
